### ISSUE TITLE
Have link to example Overleaf template open a new tab

### ISSUE THREAD

**Issue by ehumph** [fhdsl/Overleaf_Tutorial#20]
This refers to the "Overleaf" chapter. When I clicked on the link in this sentence (at the end of subsection 3.3):

'You can go to this link: https://www.overleaf.com/latex/templates/style-and-template-for-preprints-arxiv-bio-arxiv/pkzcrhzcdxmc to start with the same particular template to create a manuscript for arXiv.'

The website replaced the book. It would be helpful if the link opened in a new tab instead of replacing the contents of my current tab.

If this is a browser setting issue, then maybe the book could include keywords to search for in order to find the same template.

**Comment by carriewright11** [comment]
Thanks! I can fix that :)
