### ISSUE TITLE
Edit text for figure in 03-overleaf.Rmd

### ISSUE THREAD

**Issue by ehumph** [fhdsl/Overleaf_Tutorial#23]
The figure on slide 14 has a small grammatical error in the title. Over the large cactus the text should read "LaTeX on its own… can be a quite a challenge"

Currently the text has an apostrophe in "it's"

**Comment by carriewright11** [comment]
ooh thanks!

**Comment by carriewright11** [comment]
Good catch! I edited the slide :)
